# Generated by Django 4.2.5 on 2023-09-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('ELA', models.CharField(max_length=150)),
                ('Math', models.CharField(max_length=150)),
                ('Science', models.CharField(max_length=150)),
                ('SocialStudies', models.CharField(max_length=150)),
                ('Band', models.CharField(max_length=150)),
                ('Advisory', models.CharField(max_length=150)),
                ('PE', models.CharField(max_length=150)),
                ('Misc', models.CharField(max_length=150)),
            ],
        ),
    ]
