# Generated by Django 4.2.5 on 2023-09-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0005_alter_homework_advisory_alter_homework_band_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='ELA',
            field=models.CharField(default='None', max_length=150, null=True),
        ),
    ]
