# Generated by Django 4.2.5 on 2023-09-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0009_alter_homework_advisory_alter_homework_band_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='date',
            field=models.DateField(),
        ),
    ]
