# Generated by Django 4.2.5 on 2023-09-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0010_alter_homework_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='Spanish',
            field=models.CharField(default='None', max_length=150, null=True),
        ),
    ]
