# Generated by Django 4.2.5 on 2024-03-30 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0012_photobeforeafter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photobeforeafter',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='photobeforeafter',
            old_name='photoName',
            new_name='name',
        ),
    ]
