# Generated by Django 4.2.5 on 2024-03-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0013_rename_desc_photobeforeafter_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photobeforeafter',
            name='credit',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
