# Generated by Django 4.2.5 on 2024-05-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0014_photobeforeafter_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='photobeforeafter',
            name='event',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
