# Generated by Django 4.2.5 on 2024-09-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0015_photobeforeafter_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='Grade',
            field=models.IntegerField(default='', null=True),
        ),
    ]
