# Generated by Django 4.2.5 on 2024-09-12 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0018_alter_homework_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='Grade',
        ),
    ]
