# Generated by Django 4.2.5 on 2024-09-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0019_remove_homework_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='Grade',
            field=models.CharField(default='9', max_length=2, null=True),
        ),
    ]
