# Generated by Django 4.2.5 on 2024-10-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0020_homework_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='Grade',
        ),
    ]
